### ISSUE TITLE
Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 28

### ISSUE THREAD

**Issue by Ricolo53** [mailjet/mailjet-apiv3-php-no-composer#6]
Hello,

I just install mailjet via composer, but when I want use API to send mail, I've this kind of error

`Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 28: Resolving timed out after 2514 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in /projects/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:200 Stack trace: #0 /projects/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(155): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 /projects/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(105): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 /projects/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #3 /projects/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__inv in /projects/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 200`

How can I change timeout ?

**Comment by Ricolo53** [comment]
Finally I use classic cUrl command to call with API
